server.port=${PORT:8080}
groq.api.key=${GROQ_API_KEY}

weather.api.key =${WEATHER_API_KEY}

spring.rabbitmq.addresses=${SPRING_RABBITMQ_ADDRESSES}
spring.rabbitmq.ssl.enabled=true
spring.rabbitmq.listener.simple.auto-startup=false

spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}
spring.data.redis.username=${SPRING_REDIS_USERNAME}
spring.data.redis.password=${SPRING_REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true
spring.cache.type=simple
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.cache.type=redis

#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

agmarknet.api.key=${AGMARKNET_API_KEY}
spring.datasource.url=${db_URL}
spring.datasource.username=${db_USER}
spring.datasource.password=${db_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
